.TH GM-ASSISTANT 6 "March 4, 2014"
.SH NAME
gm-assistant \- game master assistant
.SH SYNOPSIS
.B gm-assistant
.SH DESCRIPTION
\fBGM-Assistant\fP is a software designed to be the perfect assistant for the Game Master during tabletop role-playing games. It features item-based structured plot, history, music and sound effects, along with a character table and a note editor.
It also provides useful tools such as a dice simulator and a combat manager.
.PP
It uses Qt4 for its graphical interface, the Phonon module of Qt for audio playback and XML++ and PocoZip for its saves.
.SH SEE ALSO
For more information, see \fBhttp://gmassistant.free.fr\fP
.SH AUTHOR
GM-Assistant was written by Simon Nicolas and Vincent Prat.
.PP
This manual page was written by Vincent Prat <vinceprat@free.fr>,
for the Debian project (and may be used by others).
